name: Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_ROOT_PASSWORD: password
          MYSQL_DATABASE: testing
        ports:
          - 3306:3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3

    steps:
      - uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.4'
          extensions: dom, curl, libxml, mbstring, zip, pcntl, pdo, sqlite, pdo_sqlite, bcmath, soap, intl, gd, exif, iconv, imagick, fileinfo, mysql, pdo_mysql
          coverage: none

      - name: Create storage directories
        run: |
          mkdir -p storage/framework/{sessions,views,cache/data}
          mkdir -p storage/logs
          mkdir -p storage/app/public
          mkdir -p bootstrap/cache
          mkdir -p database/settings

      - name: Copy .env
        run: |
          cp .env.example .env

      - name: Setup Composer Auth
        run: |
          echo "${{ secrets.COMPOSER_AUTH_JSON }}" | base64 -d > auth.json

      - name: Install Composer Dependencies
        run: composer install --no-progress --no-interaction --prefer-dist --optimize-autoloader

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install NPM Dependencies
        run: npm ci

      - name: Install Playwright Browsers
        run: npx playwright install --with-deps

      - name: Generate key
        run: php artisan key:generate

      - name: Directory Permissions
        run: chmod -R 777 storage bootstrap/cache

      - name: Build Assets
        run: npm run build

      - name: Run Migrations and Create Schema Dump
        env:
          DB_CONNECTION: mysql
          DB_HOST: 127.0.0.1
          DB_PORT: 3306
          DB_DATABASE: testing
          DB_USERNAME: root
          DB_PASSWORD: password
          CACHE_STORE: array
          SESSION_DRIVER: array
        run: |
          php artisan migrate --force
          php artisan schema:dump

      - name: Execute tests (Pest)
        env:
          DB_CONNECTION: mysql
          DB_HOST: 127.0.0.1
          DB_PORT: 3306
          DB_DATABASE: testing
          DB_USERNAME: root
          DB_PASSWORD: password
          CACHE_STORE: array
          SESSION_DRIVER: array
          GEO_LOCATOR_DRIVER: "null"
        run: php -d memory_limit=512M ./vendor/bin/pest --parallel

      - name: Execute Browser Tests
        env:
          DB_CONNECTION: mysql
          DB_HOST: 127.0.0.1
          DB_PORT: 3306
          DB_DATABASE: testing
          DB_USERNAME: root
          DB_PASSWORD: password
          APP_URL: http://localhost:8000
          GEO_LOCATOR_DRIVER: "null"
          CACHE_STORE: array
          SESSION_DRIVER: array
        run: php -d memory_limit=512M ./vendor/bin/pest tests/Browser --parallel

      - name: Upload Browser Test Screenshots
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: browser-screenshots
          path: tests/Browser/Screenshots
          if-no-files-found: ignore
